In [1]:
import pandas as pd
import plotly.express as px
import sqlite3

In [3]:
conn=sqlite3.connect('china_mof.db')
df=pd.read_sql_query('SELECT * FROM financial_data', conn)
conn.close()
df

,date,全国一般公共预算收入,中央一般公共预算收入,地方一般公共预算本级收入,税收收入,非税收入,国内增值税,国内消费税,企业所得税,个人所得税,...,交通运输支出,债务付息支出,全国政府性基金预算收入,中央政府性基金预算收入,方政府性基金预算本级收入,国有土地使用权出让收入,全国政府性基金预算支出,中央政府性基金预算本级支出,地方政府性基金预算支出,国有土地使用权出让收入相关支出
0,2025-12-01,216045.00,93963.00,122082.00,176363.00,39682.00,68947.00,16857.00,41304.00,16187.00,...,11977.00,13491.0,57704.0,5056.0,52648.0,41518.0,112874.0,10984.0,101890.0,47120.0
1,2025-11-01,200516.00,88464.00,112052.00,164814.00,35702.00,63629.00,15639.00,40234.00,14689.00,...,10177.00,12189.0,40274.0,3938.0,36336.0,29119.0,92124.0,9078.0,83046.0,38489.0
2,2025-10-01,186490.00,81856.00,104634.00,153364.00,33126.00,58858.00,14390.00,39182.00,13363.00,...,9199.00,10952.0,34473.0,3618.0,30855.0,24982.0,80892.0,8564.0,72328.0,33752.0
3,2025-09-01,163876.00,70837.00,93039.00,132664.00,31212.00,52271.00,12934.00,32527.00,11799.00,...,8470.00,9819.0,30717.0,3276.0,27441.0,22302.0,74924.0,8090.0,66834.0,31383.0
4,2025-08-01,148198.00,64268.00,83930.00,121085.00,27113.00,47389.00,11523.00,31477.00,10547.00,...,7128.00,8715.0,26449.0,2933.0,23516.0,19263.0,62602.0,7609.0,54993.0,26732.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
151,2011-07-01,9864.10,5228.59,4635.51,58708.04,8031.88,1754.94,548.62,2623.02,505.84,...,3299.40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
152,2011-06-01,10055.76,4459.51,5596.25,50028.43,6847.39,12431.30,3760.75,11175.36,3554.78,...,2561.17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
153,2011-05-01,10612.26,6186.38,4425.88,41896.23,4923.83,1952.29,562.00,3331.32,502.06,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
154,2011-04-01,10082.06,5214.08,4867.98,32631.52,3576.28,1826.82,561.26,2848.24,502.11,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
155,2011-03-01,7631.35,3532.68,4098.67,23438.85,2686.89,6265.00,2079.00,3434.00,2038.00,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
chart_data=df.copy()
chart_data=chart_data[["date", "M0", "M1", "M2"]]
chart_data=chart_data.sort_values(by="date", ascending=False)
chart_data["M2_pct"]=chart_data["M2"].pct_change(-11)*100
chart_data["M1_pct"]=chart_data["M1"].pct_change(-11)*100
chart_data["M0_pct"]=chart_data["M0"].pct_change(-11)*100
chart_data=chart_data[:24]
px.line(chart_data, x='date', y=["M2_pct", "M1_pct", "M0_pct"])

In [26]:
conn=sqlite3.connect('PBOC.db')
df=pd.read_sql_query('SELECT * FROM balance_sheet', conn)
conn.close()
df

,date,国外资产,外汇,货币黄金,其他国外资产,对政府债权,其中中央政府,对其他存款性公司债权,对其他金融性公司债权,对非金融性公司债权,...,国外资产_货币黄金,国外资产_其他国外资产,对政府债权_其中中央政府,储备货币_货币发行,储备货币_其他存款性公司存款,储备货币_其他存款性公司存款_非金融机构存款,储备货币_金融性公司存款,储备货币_金融性公司存款_其他存款性公司存款,储备货币_非金融机构存款,updated_at
0,2006-01-01,66269.4,65062.06,337.24,870.10,2892.43,2892.43,9080.89,18394.35,66.73,...,None,None,None,None,NaN,NaN,None,None,None,2026-04-15 12:13:49
1,2006-02-01,67214.75,65999.54,337.24,877.97,2891.88,2891.88,7871.79,18403.55,66.73,...,None,None,None,None,NaN,NaN,None,None,None,2026-04-15 12:13:49
2,2006-03-01,68440.01,67230.32,337.24,872.45,2891.88,2891.88,7808.61,18942.83,66.67,...,None,None,None,None,NaN,NaN,None,None,None,2026-04-15 12:13:49
3,2006-04-01,69110.69,67896.47,337.24,876.98,2891.88,2891.88,7125.85,19564.69,66.67,...,None,None,None,None,NaN,NaN,None,None,None,2026-04-15 12:13:49
4,2006-05-01,70662.9,69430.23,337.24,895.43,2891.88,2891.88,6959.06,20206.84,66.67,...,None,None,None,None,NaN,NaN,None,None,None,2026-04-15 12:13:49
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247,2026-08-01,,NaN,NaN,NaN,,NaN,,,NaN,...,,,,,NaN,NaN,,,,2026-04-15 12:17:31
248,2026-09-01,,NaN,NaN,NaN,,NaN,,,NaN,...,,,,,NaN,NaN,,,,2026-04-15 12:17:31
249,2026-10-01,,NaN,NaN,NaN,,NaN,,,NaN,...,,,,,NaN,NaN,,,,2026-04-15 12:17:31
250,2026-11-01,,NaN,NaN,NaN,,NaN,,,NaN,...,,,,,NaN,NaN,,,,2026-04-15 12:17:31
251,2026-12-01,,NaN,NaN,NaN,,NaN,,,NaN,...,,,,,NaN,NaN,,,,2026-04-15 12:17:31

In [70]:
chart_data=df.copy()
chart_data = chart_data.melt(id_vars='date', var_name='item', value_name='amount')
chart_data['item']=chart_data['item'].str.replace(r'^.*\_', '', regex=True)
selected=["date", "国外资产", "货币黄金", "外汇"]
selected=["date", "国外资产", "外汇"]
chart_data=chart_data[chart_data['item'].isin(selected)]
chart_data['amount']=pd.to_numeric(chart_data['amount']).fillna(0)
chart_data=chart_data[chart_data['amount']!=0]
chart_data=chart_data.groupby(['date', 'item'])['amount'].sum().unstack().reset_index()
chart_data=chart_data.sort_values(by="date", ascending=False)
for col in chart_data.columns:
    if col !='date':
        chart_data[f"{col}_pct"]=chart_data[col].astype(float).pct_change(-11)*100

chart_data=chart_data[:24]
plot_col=[col for col in chart_data.columns if 'pct' in col]
px.line(chart_data, x='date', y=plot_col)

In [69]:
chart_data

item,date,国外资产,外汇,货币黄金,国外资产_pct,外汇_pct,货币黄金_pct
242,2026-03-01,21230.42,214425.31,152481.25,-90.825737,-1.302878,3375.015554
241,2026-02-01,21479.16,213763.92,159072.75,-90.742367,-1.943930,3538.019124
240,2026-01-01,21654.37,212922.61,151746.07,-90.683835,-2.625360,3387.838105
239,2025-12-01,226260.02,212391.23,4486.37,-2.829889,-3.163700,3.910569
238,2025-11-01,226231.76,212418.36,4476.69,-3.011611,-3.410616,4.481071
237,2025-10-01,226776.72,213003.00,4467.16,-2.912272,-3.331762,5.771152
236,2025-09-01,227468.32,213680.60,4457.98,-2.799134,-3.195009,6.329724
235,2025-08-01,228117.35,214382.04,4449.23,-2.658322,-2.979832,6.121023
234,2025-07-01,229023.79,215090.02,4433.50,-2.412529,-2.775664,5.745838
233,2025-06-01,229842.47,215804.96,4418.24,-2.193341,-2.592813,5.381863
232,2025-05-01,230485.43,216519.32,4403.09,-2.056926,-2.424699,5.020512
231,2025-04-01,231412.80,217255.89,4387.93,-1.780735,-2.251810,4.658923
230,2025-03-01,232015.68,218001.72,4372.51,-1.555755,-1.999875,4.291132
229,2025-02-01,232438.67,218663.31,4350.72,-1.466230,-1.804553,4.040902
228,2025-01-01,232849.40,219330.18,4317.53,-1.065193,-1.282947,3.881671
227,2024-12-01,233256.54,219918.95,4284.69,-0.503759,-0.638502,4.508967
226,2024-11-01,233579.18,220344.35,4223.42,0.013132,-0.049670,4.207872
225,2024-10-01,234018.82,220733.04,4192.60,0.525051,0.440978,4.554398
224,2024-09-01,234347.05,220966.47,4192.60,0.991522,0.896955,6.040027
223,2024-08-01,234685.65,221230.64,4192.60,1.622496,1.437703,8.748149
222,2024-07-01,234996.75,221549.32,4192.60,1.477021,1.780383,11.789550
221,2024-06-01,235325.91,221899.72,4192.60,1.548888,1.870770,15.395307
220,2024-05-01,235608.36,222260.78,4192.60,1.741980,2.079177,18.436701
219,2024-04-01,235682.32,222450.45,4192.60,1.820116,2.124774,21.322083

In [20]:
conn=sqlite3.connect('china_mof.db')
df=pd.read_sql_query('SELECT * FROM financial_data', conn)
conn.close()
df.columns

Index(['date', '全国一般公共预算收入', '中央一般公共预算收入', '地方一般公共预算本级收入', '税收收入', '非税收入',
       '国内增值税', '国内消费税', '企业所得税', '个人所得税', '进口货物增值税消费税', '关税', '出口退税',
       '城市维护建设税', '车辆购置税', '印花税', '资源税', '契税', '房产税', '城镇土地使用税', '土地增值税',
       '耕地占用税', '环境保护税', '其他各项税收收入', '全国一般公共预算支出', '中央一般公共预算本级支出',
       '地方一般公共预算支出', '教育支出', '科学技术支出', '文化旅游体育与传媒支出', '社会保障和就业支出', '卫生健康支出',
       '节能环保支出', '城乡社区支出', '农林水支出', '交通运输支出', '债务付息支出', '全国政府性基金预算收入',
       '中央政府性基金预算收入', '方政府性基金预算本级收入', '国有土地使用权出让收入', '全国政府性基金预算支出',
       '中央政府性基金预算本级支出', '地方政府性基金预算支出', '国有土地使用权出让收入相关支出'],
      dtype='object')

In [45]:
chart_data=df.copy()
chart_data['date']=pd.to_datetime(chart_data['date'])


def ployt_area(plot_y):
    chart_data=chart_data[plot_y]
    chart_data=chart_data.set_index('date')
    chart_data=chart_data.stack().rename("amount").reset_index().rename(columns={'level_1': 'item'})
    total_per_period = chart_data.groupby('date')['amount'].transform('sum')
    # 2. 測算出百分比
    chart_data['percentage'] = (chart_data['amount'] / total_per_period) * 100
    fig=px.area(chart_data, x='date', y='percentage', color='item',
            #    barmode='relative', 
            )

    fig.update_layout(hovermode="x unified",
                                xaxis=dict(
                                # %Y-%m 代表顯示 2024-12
                                hoverformat="%b-%Y" 
                            )
            )
    fig.show()

In [ ]:
plot_y=['date', '地方一般公共预算本级收入', '中央一般公共预算收入']
ployt_area(plot_y)

          date        item     amount
0   2025-12-01  全国一般公共预算收入  216045.00
1   2025-12-01  中央一般公共预算收入   93963.00
2   2025-11-01  全国一般公共预算收入  200516.00
3   2025-11-01  中央一般公共预算收入   88464.00
4   2025-10-01  全国一般公共预算收入  186490.00
..         ...         ...        ...
307 2011-05-01  中央一般公共预算收入    6186.38
308 2011-04-01  全国一般公共预算收入   10082.06
309 2011-04-01  中央一般公共预算收入    5214.08
310 2011-03-01  全国一般公共预算收入    7631.35
311 2011-03-01  中央一般公共预算收入    3532.68

[312 rows x 3 columns]

In [ ]:
plot_y=['date','税收收入', '非税收入']

In [ ]:
plot_y=['date', '国内增值税', '国内消费税', '企业所得税', '个人所得税', '进口货物增值税消费税', '关税', '出口退税',
       '城市维护建设税', '车辆购置税', '印花税', '资源税', '契税', '房产税', '城镇土地使用税', '土地增值税',
       '耕地占用税', '环境保护税', '其他各项税收收入']